### ISSUE TITLE
TODO v1

### ISSUE THREAD

**Issue by RSS1102** [RSS1102/cherry-markdown-v2#4]
- v0.1
- [ ] 优化save保存文件操作(另存为添加默认文件名，save要添加是否已保存状态)。
- [ ] 添加页脚 显示文件路径
- [ ] 添加title 显示文件标题
- [ ] link跳转
- [ ] 图片展示
- [ ] 保存文件状态提示
- [ ] 新建文件增加二次弹窗提示保护
- [ ] Window menu 添加 about=>添加客户端说明和商标
- [ ] 调整窗口大小
- [ ] 屏蔽右键客户端操作。
- [ ] 增加部分快捷键用来处理文件（保存，另存为，新文件）
- [ ] 开屏 loading
- [ ] 优化精简toolbar
- [ ] 增加面板展示文件目录(参考:vscode 和 https://github.com/lgou2w/HoYo.Gacha) 这里目前是对于已打开文件路径记录,(如果不存在文件移除并添加提示)。
---
- v0.2
- [ ] Window下右键/默认使用客户端打开md文件。
- [ ] 对于文件面板文件进行 标记tag分类 filter 展示。(创建tag，标记tag，未分类)。
- [ ] 获取系统内所有的md相关文件进行展示。
- [ ] 增强cherry-markdown快捷键(增加可自定义cherry-markdown能力面板)。
- [ ] 改变客户端主题和cherry-markdown一致。
- [ ] 图片点击放大预览。
- [ ] 全屏模式切换。
---
- v0.3
- [ ] 插件化自定义主题。
- [ ] 自定义nsis安装页面
- [ ] mac认证（待定）
